FROM registry.orientsoft.cn/library/jupyterlab-chinese:20190425

LABEL maintainer="Lirongfan <lirongfan@orientsoft.cn>"

RUN conda install xeus-cling -c conda-forge

# COPY ./xcpp.ipynb ./jupyter_chinese