FROM registry.datadynamic.io/library/jupyterlab-chinese:20190227_2

COPY ./files/ ./

RUN bash ./temporary/p_root.sh

USER jovyan

RUN bash -c '/bin/echo -e "y\n" | bash ./temporary/p_user.sh'\
    && rm -r temporary